"""Add token blacklist to the database

Revision ID: f635f7be72d1
Revises: 8724ff7c15c5
Create Date: 2024-01-25 00:54:12.090999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f635f7be72d1'
down_revision = '8724ff7c15c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=200), nullable=False),
    sa.Column('sibling_jti', sa.String(length=200), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=True),
    sa.Column('owners_id', sa.Integer(), nullable=False),
    sa.Column('owners_account_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
